openapi: 3.0.0
info:
  title: API del sistema MatriCool
  version: 1.0.0
  description: Esta API permite gestionar la capa de datos.

servers:
  - url: http://localhost:4321

tags:
  - name: Actividades
  - name: Asistencia
  - name: Config
  - name: DataUser
  - name: EncargadoAlumnos
  - name: Horarios
  - name: MateriaProfesor
  - name: Materias
  - name: MensajeReceptors
  - name: Mensajes
  - name: Notas
  - name: SeccionAlumnos
  - name: Secciones
  - name: SeccionProfesor
  - name: User
  - name: Auth

paths:
  $ref: './paths.yaml'

components:
  $ref: './schemas.yaml'
